### ISSUE TITLE
Invalid params generated for patch/update where table/GSI specified with Composite Attribute Templates

### ISSUE THREAD

**Issue by rogersillito** [tywalch/electrodb#343]
**Describe the bug**
We need to do an update to a field "status" (that is itself the primary key of a GSI) where that update includes a `ConditionExpression` to ensure the status has the expected value before applying the update.  Our index definitions use [attribute templates](https://electrodb.dev/en/modeling/indexes/#composite-attribute-templates) (rationale below!).   When we try to patch (or update) in this way, the params that are generated result in an update expression where setting of the status field is duplicated twice - this results in a DynamoDB error when the patch/update is executed.

![image](https://github.com/tywalch/electrodb/assets/2572893/00087651-0cbe-4cc9-b15b-2c434890d971)

If I **_remove_** the GSI, then the patch/upate params are generated correctly, albeit we can't then benefit from that index ([Playground demo of this](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAckRwjVSzABGNgNzijUPrgVUGFwRSAF5bBkcsfTgAfQZpaQRjBg0fXA9xUDAAFQZcAGshNQ0qTWExb18FAEFI6OqEpKMUrDSwML44FlV1LQAKUTAlQaGwSVhEAC5h0dH+Es1pmwiNesbk1L4bfBHZ6IxcVr4lgEZt3dHiDEMTJax1TD4GBAbpAAU5AIRz2dMd2ZSTiwLlQVDw00UFyGqCuT0kcAhUNGpWkCNsfmwfAA5j9ZqMuDgEDAlqgtv88UNyGgsORiWAnOhyb8maN4okNkcANJwRYzCn0zSopYY+44lmzAmIOnLfK4ilU1A0uB0hlwcVgP5IvwpGGI-kCoVgADaSNmNh0b2qAHUAHIxABKKgAigBVFQ6bIqAAicv55sttoAkjaAOIxADCAHkvSoAEIuwMAGR96rNFutNuDYcd1S9wfdOgjAAkVOHOb6Kf6M96K3ibI6IJGAGoqB3Ot0emup0b1lSNptZiPRuMJ5O1s0AMWqSa7prAAF0wHkwJU-N3JUThVRx2Q4NTadNVerNRS6FA-DaGPC9fyUWibCLsTuN9K6GS5+QGDBI3wELyjx+e6Kge9IYIySInniuDSAwLB8IGdKQvqd5bpiYpzi+wpYLWkGzOQ4zRAhN4Uih6JAk+66EtK2A4SyuFgPc8AAB7gnyswuJoLqwleaJIfy0j5MR-KYbYpI7kM3gyOe7BokaNgwo8PE2PO3ZDGCMgICk94ACSKApGBwnApjiSueSiksfA+HAO70bMBRCRSIkyiZkmyIcYLTHJbJNC0PjcpoymqfScAaVpSy6d5HJ+TyxlBc0hzYhZVk2cedHkpBygBEEZg7AAlJ4oi1KscCvD5my4AAdDBVBGHQfR8fphlLDaeBUHIVq4pFzSbP5SxOAwvhcJg5ymLlIwVcQVD1Rc2pULqtjpkGoZDjG8ZJimIyjeNLB0JgcB9PVRABHNQh-EoYB7hquXtAAfBdyB9LNMKEFWtptq67qej6uVjUMFVYlAfT5aIQA)).

**ElectroDB Version**
2.12.2

**ElectroDB Playground Link**
[ElectroDB Playground Example "patch" mutation](https://electrodb.fun/?#code/PQKgBAsg9gJgpgGzARwK5wE4Es4GcA0YuccYGeqCALgUQBYCG5YA7llXWAGbZwB2MXGBDAAUKKwBbAA5QMVMAG8wAUT5V2AT0IBlTADcsAY1IBfbhiiSwAckRwjVSzABGNgNzijUPrgVUGFwRSAF5bBkcsfTgAfQZpaQRjBg0fXA9xUDAAFQZcAGshNQ0qTWExb18FAEFI6OqEpKMUrDSwML44FlV1LQAKUTAlQaGwSVhEAC5h0dH+Es1pmwiNesbk1L4bfBHZ6IxcVr4lgEZt3dHiDEMTJax1TD4GBAbpAAU5AIRz2dMd2ZSTiwLlQVDw00UFyGqCuT0kcAhUNGpWkCNsfmwfAA5j9ZqMuDgEDAlqgtv88UNyGgsORiWAnOhyb8maN4okNkcANJwRYzCn0zSopYY+44lmzAmIOnLfK4ilU1A0uB0hlwcVgP5IvwpGGI-kCoVgADaSNmNh0b2qAHUAHIxABKKgAigBVFQ6bIqAAicv55sttoAkjaAOIxADCAHkvSoAEIuwMAGR96rNFutNuDYcd1S9wfdOgjAAkVOHOb6Kf6M96K3ibI6IJGAGoqB3Ot0emup0b1lSNptZiPRuMJ5O1s0AMWqSa7prAAF0wHkwJU-N3JUThVRx2Q4NTadNVerNRS6FA-DaGPC9fyUWibCLsTuN9K6GS5+QGDBI3wELyjx+e6Kge9IYIySInniuDSAwLB8IGdKQvqd5bpiYpzi+wpYLWkGzOQ4zRAhN4Uih6JAk+66EtK2A4SyuFgPc8AAB7gnyswuJoLqwleaJIfy0j5MR-KYbYpI7kM3gyOe7BokaNgwo8PE2PO3ZDGCMgICk94ACSKApGBwnApjiSueSiksfA+HAO70bMBRCRSIkyiZkmyIcYLTHJbJNC0PjcpoymqfScAaVpSy6d5HJ+TyxlBc0hzYhZVk2ce6ocToARULqbF4oxcBMUsKxRHAAC0kXNJsuAlRxJXall6TdgJDl4k5fguVYbkyZ5D6ZTCgVzmpIWJGFti6XVMKxQNpkJViSWdClEF0eSkHKAEQRmDsACUniiLUqxwK8PmVQAdDBVBGHQfR8fphlLDaeBUHIVq4uVvl8P5SxOAwvhcJg5ymJtIzHcQVBXRc424Es6ZBqGQ4xvGSYpiMANAywdCYHAfRXUQvVCH8ShgHuGqbe0AB8hPIH0EOEFWtptq67qej6m2A0Mx1YlAfTbaIQA)

**Entity/Service Definitions**

```
{
    model: {
      entity: 'activeApplication',
      version: '1',
      service: 'internalAppPortal',
    },
    attributes: {
      username: {
        type: 'string',
        field: 'un',
        required: true,
      },
      applicationKey: {
        type: 'string',
        field: 'ak',
        required: true,
      },
      status: {
        type: [
          'SPAWN_REQUESTED',
          'SPAWNING_CODEBUILD',
          'SPAWNING_READINESS_CHECK',
          'SPAWNED',
          'REMOVE_REQUESTED',
          'REMOVING_CODEBUILD',
          'FAILED',
        ] as const,
        field: 'st',
        required: true,
      },
      hostName: {
        type: 'string',
        field: 'hn',
        readOnly: true,
        required: true,
      },
      spawnId: {
        type: 'string',
        field: 'si',
      },
      removeId: {
        type: 'string',
        field: 'ri',
      },
    },
    indexes: {
      byUsername: {
        pk: {
          field: 'un',
          composite: ['username'],
          template: '${username}',
          casing: 'none',
        },
        sk: {
          field: 'ak',
          composite: ['applicationKey'],
          template: '${applicationKey}',
          casing: 'none',
        },
      },
      byStatus: {
        index: 'active-applications-by-status',
        pk: {
          field: 'st',
          composite: ['status'],
          template: '${status}',
          casing: 'none',
        },
      },
    },
  }
```

**Expected behavior**
The patch params should be generated without the duplicated setting of "status".

**Errors**

```
{
  "message": "Error thrown by DynamoDB client: \"Invalid UpdateExpression: Two document paths overlap with each other; must remove or rewrite one of these paths; path one: [st], path two: [__edb_e__]\" - For more detail on this error reference: https://electrodb.dev/en/reference/errors/#aws-error",
  "name": "ElectroError",
  "ref": {
    "code": 4001,
    "section": "aws-error",
    "name": "AWSError"
  },
  "code": 4001,
  "date": 1704387127434,
  "isElectroError": true
}
```
stack trace:

```
    at Entity.go (C:\DEV\internal-app-portal\admin-app\node_modules\electrodb\src\entity.js:497:20)
    at Object.action (C:\DEV\internal-app-portal\admin-app\node_modules\electrodb\src\clauses.js:1240:23)
    at current.<computed> [as go] (C:\DEV\internal-app-portal\admin-app\node_modules\electrodb\src\clauses.js:1343:41)
    at executeDbOps (webpack-internal:///(api)/./electrodbtest.ts:199:71)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Additional context**
We have a very simple use-case where our app has only a single entity and a single DynamoDB table needed to store it in.   Our keys and access patterns naturally align with the primary key/sort key requirement of DynamoDB.   For this reason we would prefer not to use the "default", Single Table Design orientated behaviour of electrodb around indexes which embeds the additional attribute metadata within the pk/sk values.  This is why we are going against your recommendation and making use of index attribute _templates_. If there's an alternative way we could get to the same place and avoid the issue we seem to have hit, that would be good to know?

**Comment by tywalch** [comment]
Hi @rogersillito 👋 

Oh darn, thank you for raising this, I will take a look and get back to you soon!

**Comment by kennethlili** [comment]
Hi. I am struggling into this issue. I am using existing attributes as my pk and sk for GSI and calling upsert will return this error, any solution to resolve this issue? Thanks in advance

**Comment by tywalch** [comment]
@eanmclaughlin thank you for the poke, I will look at this this weekend 👍

**Comment by tywalch** [comment]
@eanmclaughlin @kennethlili @rogersillito This fix is in, lmk if you experience any further issues. It goes without saying that this ticket was open much longer than any ticket should be open for, so I am sorry for that. Fwiw, my daughter was born <1mo after this ticket was opened, and she has been my number one project ever since 😅

**Comment by eanmclaughlin** [comment]
@tywalch Thank you for the quick fix over the weekend! The new version looks great on our side. 

Congrats on your daughter; I hope she's happy, healthy, and not _too_ much of a handful :)

**Comment by rogersillito** [comment]
thanks @tywalch - all the best to you & family!
